### ISSUE TITLE
NameError: name 'bool_to_bytes' is not defined

### ISSUE THREAD

**Issue by sidharthjs** [ronhanson/python-dcitools#3]
Hi,

bin/doremiapi fails. Error:

```
Traceback (most recent call last):
  File "bin/doremiapi", line 15, in <module>
    import dcitools.devices.doremi.snmp as doremi_snmp
  File "/usr/local/lib/python2.7/dist-packages/dcitools-0.7.0-py2.7.egg/dcitools/devices/doremi/__init__.py", line 1, in <module>
    from . import commands
  File "/usr/local/lib/python2.7/dist-packages/dcitools-0.7.0-py2.7.egg/dcitools/devices/doremi/commands.py", line 12, in <module>
    from . import requests
  File "/usr/local/lib/python2.7/dist-packages/dcitools-0.7.0-py2.7.egg/dcitools/devices/doremi/requests.py", line 88, in <module>
    E('enable', bool_to_bytes),
NameError: name 'bool_to_bytes' is not defined
```

Is there any locked version of tbx to be used with this repo? Please assist.

**Comment by ronhanson** [comment]
It was indeed a bug and it has been solved in latest version, with a requirement update.
Sorry about that and the delay in fixing the repo.
Also the doremiapi has been added as a command script so it is easier to find/execute.
