### ISSUE TITLE
Running into an issue : ModuleNotFoundError: No module named 'pysnmp.entity.rfc3413.oneliner'

### ISSUE THREAD

**Issue by mthvrs** [ronhanson/python-dcitools#7]
Hi,

Please excuse me if this is a mistake on my part but I don't have the best understanding of python once stuff breaks!

I'm trying to use the bin/doremiapi script but upon running it I am facing the following issue, seemingly because the import could not be resolved. 

`C:\Users\mathi\Downloads\python-dcitools-0.7.2>py bin/doremiapi --help
Traceback (most recent call last):
  File "C:\Users\mathi\Downloads\python-dcitools-0.7.2\bin\doremiapi", line 15, in <module>
    import dcitools.devices.doremi.snmp as doremi_snmp
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python311\Lib\site-packages\dcitools\devices\doremi\__init__.py", line 3, in <module>
    from . import snmp
  File "C:\Users\mathi\AppData\Local\Programs\Python\Python311\Lib\site-packages\dcitools\devices\doremi\snmp.py", line 10, in <module>
    from pysnmp.entity.rfc3413.oneliner import cmdgen
ModuleNotFoundError: No module named 'pysnmp.entity.rfc3413.oneliner'`

If this is an error on my part I'd be very grateful for any sort of guidance! 

Thank you for making this project, I really hope to be able to use it soon as it sounds like a perfect match for my needs. 

:)

**Comment by sherpadown** [comment]
Hello,
You need to install pysnmp library.
Did you launch "pip install -r requirements.txt" before ?
